name: Sample github action workflow

on:
  push:
    branches: ['main', 'master']
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        service:
          - appointment-service
          - doctor-service
          - patient-service
          - report-service
          - user-service
    defaults:
      run:
        working-directory: healthcare-microservices/${{matrix.service}}
      
    steps:
      - name: checkout code
        timeout-minutes: 5
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        timeout-minutes: 10
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: build the code
        run : mvn -B clean verify
        
        


    
